### ISSUE TITLE
Colorize buttons creates some random color artifacts 

### ISSUE THREAD

**Issue by DjoleDzele** [alexankitty/FancyTasks#19] opened 2022-10-30 09:28 UTC
When using option to colorize buttons, and then hover over some of them it creates these kinds of artifacts randomly

![Screenshot_20221030_102344](https://user-images.githubusercontent.com/48789138/198871602-4532ce42-a65e-4976-9631-29139c818357.png)

**Comment by b1scu1t** [comment] 2022-10-30 13:31
This looks like a duplicate of https://github.com/alexankitty/FancyTasks/issues/3

**Comment by DjoleDzele** [comment] 2022-10-30 13:33
that other one might be connected to Wayland, im on X11, but not sure

**Comment by alexankitty** [comment] 2022-11-14 02:31
This is definitely a duplicate, and I don't have a way of reliably recreating it, but I'll note that #3 occurs regardless of the display server. Closing this isuse, let's continue the discussion on #3

**Closed by alexankitty** 2022-11-14 02:31 UTC
