### ISSUE TITLE
Putting widget on desktop and dragging it on the bar crashes KDE

### ISSUE THREAD

**Issue by ziomek64** [alexankitty/FancyTasks#7] opened 2022-10-28 18:54 UTC
So, when I put the widget on the desktop and then drag it on the bar it crashes, my whole screen goes black and it restarts KDE i think IDK and when I put it on the left corner of the bar after crash it will be on the right for some damn reason. Again nvidia and X11

**Comment by alexankitty** [comment] 2022-10-28 19:09
Alright. I'll look into it. Plasma crashes are difficult to troubleshoot with plasmoids in my experience so hopefully I can find a rhyme or reason for this and that it's not an upstream issue.

**Comment by ziomek64** [comment] 2022-10-28 19:13
@alexankitty It happens only when dragging widget from desktop on bar. Just adding on bar doesn't crash anything though, pretty weird

**Comment by alexankitty** [comment] 2022-10-28 19:15
Works fine as a panel but not as a floating widget? Am I understanding that right? If so I might know why.

**Comment by ziomek64** [comment] 2022-10-28 19:16
@alexankitty no both work fine on its own. It is ONLY when dragging it from desktop to a panel

**Comment by alexankitty** [comment] 2022-10-28 19:18
I was able to replicate it myself, and it actually crashed both ways.

**Comment by ziomek64** [comment] 2022-10-28 19:22
@alexankitty I haven't actually checked moving it from panel to floating state lol. But yeah, as you can see the issue exists.

**Comment by alexankitty** [comment] 2022-10-28 19:25
Alright, the good thing is it can be easily reproduced. I'll see what I can do about fixing it.

**Comment by alexankitty** [comment] 2022-10-29 04:32
This crash is caused by the state switching that controls indicator positions. I'll work on a fix for this.

**Comment by alexankitty** [comment] 2022-10-29 05:08
Looking into this further I made a mistake. The state switching is still at least important for the floating dock but it actually seems the crashing stems from putting the computer to sleep and waking it and then moving it.
I made this realization when I was doing testing and forgot to replace the plasmoid and thought commenting out my states fixed it, but instead the crashing wasn't reproduceable until I made my computer sleep.

**Comment by alexankitty** [comment] 2022-10-29 05:12
Actually, I'm not sure anymore. maybe I got a bit flip or something I can't reproduce again. I've pushed the commit to the bug-fixing branch here https://github.com/alexankitty/FancyTasks/tree/bug-fixing I'll include an update script to allow you to update after cloning the repo so you can test and let me know if it's working on your end before I merge.

**Comment by alexankitty** [comment] 2022-10-29 06:31
Additional update for a default case for the indicators if the override isn't selected.

**Closed** 2022-10-29 06:48 UTC
Labels: bug, priority
